cat("Welcome to the 2024 IOTC Yellowfin assessment project.\n")
require(dplyr)
require(purrr)
require(ggplot2)
require(stringr)
library(reshape)
library(r4ss)
library(here)
library(tidyr)
library(RColorBrewer)
library(gridExtra)